Initial work on windows action.

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -53,6 +53,31 @@ jobs:
     - name: Install dependencies (Windows)
       run: |
         ./vcpkg/vcpkg.exe install apr:x64-windows apr-util:x64-windows sqlite3:x64-windows zlib:x64-windows utf8proc:x64-windows openssl:x64-windows berkeleydb:x64-windows lz4:x64-windows python2:x64-windows
+      if: "matrix.os == 'windows-latest'"
+    - name: Locate & Exec vcvarsall.bat
+      run: |
+        $VCVarsAll = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find "VC\Auxiliary\Build\vcvarsall.bat"
+        if (-not $VCVarsAll) {
+          Write-Error "vcvarsall.bat not found" -Category NotInstalled
+          exit 1
+        }
+        $Token = "#####ENV#####"
+        $enc = [Console]::OutputEncoding
+        [Console]::OutputEncoding = [Text.Encoding]::Unicode
+        $VCVarsAllResult = cmd /U /C "`"$VCVarsAll`" x64 && echo $TOKEN&& set"
+        [Console]::OutputEncoding = $enc
+        $TokenIndex = $VCVarsAllResult.IndexOf($Token)
+        if ($TokenIndex -eq -1) {
+          Write-Error "vcvarsall failed."
+          exit 1
+        }
+        $VCVarsAllResult | Select-Object -Skip ($TokenIndex + 1) | ForEach-Object {
+          $k, $v = $_ -split "=", 2
+          Write-Output "::set-env name=$k::$v"
+        }
+      shell: pwsh
+    - name: Install serf (Windows)
+      run: |
         curl https://downloads.apache.org/serf/serf-1.3.9.zip -o serf.zip
         unzip -q serf.zip
         cd serf-1.3.9
